// Client-safe example allowlist. The server still filters discovery and execution
// by the connection's explicit grants; these names never grant new permissions.
export const publicationTools = [
  "website_publish",
  "website_settings_publish",
  "calendar_publish",
  "calendar_schedule_publish",
  "calendar_page_publish",
  "forms_publish",
  "events_publish",
  "events_prize_publish",
  "directory_publish",
  "projects_publish",
];
export const contentTools = [
  "automation_capabilities",
  "automation_prompt",
  "automation_website_prompt",
  "automation_event_prompt",
  "automation_project_prompt",
  "automation_review_prompt",
  "website_context",
  "website_design",
  "website_list",
  "website_get",
  "website_create",
  "website_save",
  "website_preview",
  "website_revision_get",
  "website_restore",
  "website_duplicate",
  "website_locale_create",
  "website_settings_save",
  "source_read",
  "content_import",
  "import_get",
  "media_list",
  "media_get",
  "media_upload",
  "media_inspect",
  "media_metadata_save",
  "forms_list",
  "forms_get",
  "forms_create",
  "forms_save",
  "events_list",
  "events_get",
  "events_create",
  "events_save",
  "events_blueprints",
  "events_prepare_preview",
  "events_prepare",
  "events_workspace",
  "events_form_create",
  "events_packages",
  "events_package_save",
  "events_prizes",
  "events_prize_save",
  "events_propose_settings",
  "events_proposals",
  "directory_list",
  "directory_create",
  "directory_save",
  "projects_list",
  "projects_get",
  "projects_create",
  "projects_save",
  "calendar_read",
  "calendar_create",
  "calendar_save",
  "calendar_archive",
  "calendar_restore",
  "calendar_schedule_create",
  "calendar_schedule_save",
  "calendar_schedule_archive",
  "calendar_schedule_restore",
  "calendar_page_save",
  ...publicationTools,
];
export const openAiApprovalPolicy = {
  never: {
    tool_names: contentTools.filter((name) => !publicationTools.includes(name)),
  },
  always: { tool_names: publicationTools },
};
export function clientExamples(origin: string) {
  const endpoint = `${new URL(origin).origin}/api/mcp`;
  return {
    claudeCode: JSON.stringify(
      {
        mcpServers: {
          rotapress: {
            type: "http",
            url: endpoint,
            headers: { Authorization: "Bearer ${ROTAPRESS_MCP_KEY}" },
          },
        },
      },
      null,
      2,
    ),
    codex: `[mcp_servers.rotapress]\nurl = ${JSON.stringify(endpoint)}\nbearer_token_env_var = "ROTAPRESS_MCP_KEY"\nenabled_tools = ${JSON.stringify(contentTools)}\n`,
    desktop: JSON.stringify(
      {
        mcpServers: {
          rotapress: {
            command: "node",
            args: [
              "--env-file=/absolute/private/rotapress-mcp.env",
              "/absolute/path/to/RotaPress/scripts/mcp_bridge.mjs",
            ],
          },
        },
      },
      null,
      2,
    ),
    openai: `import os\nfrom openai import OpenAI\n\nresponse = OpenAI().responses.create(\n    model=os.environ["OPENAI_MODEL"],\n    input="Call automation_prompt for my reference URL and prepare private drafts using verified club facts. Return review links. Publish only if I explicitly ask.",\n    tools=[{\n        "type": "mcp",\n        "server_label": "rotapress",\n        "server_url": ${JSON.stringify(endpoint)},\n        "authorization": os.environ["ROTAPRESS_MCP_KEY"],\n        "allowed_tools": ${JSON.stringify(contentTools)},\n        "require_approval": ${JSON.stringify(openAiApprovalPolicy)},\n    }],\n)\nprint(response.output_text)\nfor item in response.output:\n    if item.type == "mcp_approval_request":\n        # Present the tool and arguments to the user in your application.\n        # Continue with mcp_approval_response only after their decision.\n        print("Approval required:", item.id, item.name, item.arguments)`,
    anthropic: `import os\nimport anthropic\n\nresponse = anthropic.Anthropic().beta.messages.create(\n    model=os.environ["ANTHROPIC_MODEL"],\n    max_tokens=4096,\n    messages=[{"role": "user", "content": "Call automation_prompt for my reference URL and prepare private drafts using verified club facts. Return review links."}],\n    mcp_servers=[{\n        "type": "url",\n        "name": "rotapress",\n        "url": ${JSON.stringify(endpoint)},\n        "authorization_token": os.environ["ROTAPRESS_MCP_KEY"],\n    }],\n    tools=[{\n        "type": "mcp_toolset",\n        "mcp_server_name": "rotapress",\n        "default_config": {"enabled": False},\n        "configs": {name: {"enabled": True} for name in ${JSON.stringify(contentTools)}},\n    }],\n    betas=["mcp-client-2025-11-20"],\n)\nfor block in response.content:\n    if block.type == "text":\n        print(block.text)`,
  };
}
